plan/home/models.py
import sqlalchemy as sa
import sqlalchemy.orm as so

from plan.conf.boost import db


class Discipline(db.Model):
    campus: so.Mapped[str] = so.mapped_column(sa.String(9), primary_key=True)
    discipline: so.Mapped[str] = so.mapped_column(
        sa.String(38), primary_key=True
    )
    department: so.Mapped[str] = so.mapped_column(
        sa.String(24), primary_key=True
    )
    schedule: so.Mapped[str] = so.mapped_column(sa.String(6), primary_key=True)

plan/home/routes.py
import sqlalchemy as sa
from flask import Blueprint, render_template

from plan.conf.boost import db
from plan.home.models import Discipline

bp_home_routes = Blueprint("bp_home_routes", __name__)


@bp_home_routes.route("/")
def home():
    disciplines = db.session.scalars(
        sa.select(Discipline).order_by(Discipline.campus)
    ).all()
    return render_template("home/home.html", disciplines=disciplines)

plan/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Basic Page Needs ––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">

    <title>
      Encargos didáticos 2024/2
    </title>

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile Specific Metas –––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS --------------–––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script defer src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="https://ime.ufg.br" target="_blank">IME/UFG</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('bp_home_routes.home') }}">Início</a></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Coleções</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

  </body>

</html>

plan/templates/home/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="ten columns" style="margin-top: 10%">
      <p>

      <table class="table table-striped" style="margin-top: 5%">
        <thead>
          <tr>
            <th scope="col">
              Câmpus
            </th>
            <th scope="col">
              Disciplina
            </th>
            <th scope="col">
              Departmento
            </th>
            <th scope="col">
              Horário
            </th>
          </tr>
        </thead>
        <tbody>
          {% for discipline in disciplines %}
          <tr>
            <td>
                {{ discipline.campus }}
            </td>
            <td>
              {{ discipline.discipline }}
            </td>
            <td>
              {{ discipline.department }}
            </td>
            <td>
              {{ discipline.schedule }}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      </p>
    </div>
  </div>
</div>

{% endblock %}

plan/templates/home/welcome.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="ten columns" style="margin-top: 10%">
      <p>

      <table class="table table-striped" style="margin-top: 5%">
        <thead>
          <tr>
            <th scope="col">
              Câmpus
            </th>
            <th scope="col">
              Disciplina
            </th>
            <th scope="col">
              Departmento
            </th>
            <th scope="col">
              Horário
            </th>
          </tr>
        </thead>
        <tbody>
          {% for discipline in disciplines %}
          <tr>
            <td>
                {{ discipline.campus }}
            </td>
            <td>
              {{ discipline.discipline }}
            </td>
            <td>
              {{ discipline.department }}
            </td>
            <td>
              {{ discipline.schedule }}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      </p>
    </div>
  </div>
</div>

{% endblock %}